# Generated by Django 3.2.7 on 2021-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
    ]
