# Generated by Django 3.2.7 on 2022-03-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
